### ISSUE TITLE
Impossible d'accéder à l'API

### ISSUE THREAD

**Issue by armaldio** [lupin012345/epitech-api-public#8]
Bonjour, 

J'essaie d'accéder à l'API pour retrouver le planning complet.
Cependant j'obtiens cette erreur : 

XMLHttpRequest cannot load http://epitech-api.herokuapp.com/login?login=xxx&password=xxx Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://qefqef-armaldio1.c9users.io' is therefore not allowed access.

Je fais qqchose de mal ?

```javascript
var data = null;

var xhr = new XMLHttpRequest();
xhr.withCredentials = true;

xhr.addEventListener("readystatechange", function() {
	if (this.readyState === 4) {
		console.log(this.responseText);
	}
});

xhr.open("POST", "http://epitech-api.herokuapp.com/login?login=xxx&password=xxx");

xhr.send(data);
```

**Comment by lupin012345** [comment]
Bonjour !

À relire le code de l'api il me semble effectivement qu'il n'y ait pas de header
Access-Control-Allow-Origin renvoyé par l'API pour autoriser les CORS.

Si jamais tu as des propositions de changements de manière générale n'hésite pas à me faire des pull-requests, l'API est pas toujours testée à 100% en dehors des périodes du projet EpiAndroid donc il est possible que l'intra change le format de certaines données et que je doive les changer sur l'Api aussi.

Normalement tu ne devrais plus avoir de soucis en tapant sur le heroku, j'ai ajouté les headers

**Comment by armaldio** [comment]
Ah, super merci, je teste ça !
Vaut mieux que je host moi même le script ou je peut utiliser ton heroku sans probleme ?

**Comment by lupin012345** [comment]
Le heroku est stable comme il est testé chaque année, mais si tu as des changement à faire ça peut être intéressant pour toi de la cloner chez toi si tu veux faire des modifications

**Comment by armaldio** [comment]
Ok :)

Je viens de retester, 

- Sans `xhr.withCredentials = true;` j'obtiens un 401 et 

```json
{"error": {"code": 401, "message": "No token or login/password"}}
```

- Avec : 

```
A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'https://qefqef-armaldio1.c9users.io' is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute.
```

**Comment by lupin012345** [comment]
Malheureusement je peux pas faire mieux qu'une wildcard sur le Allow-origin, la solution serait que tu déploies l'API quelque part chez toi et que tu mettes ton domaine uniquement dans le Allow-origin

**Comment by armaldio** [comment]
Jvais faire ça, merci :)
